site_name: Flashy

site_url: http://Inflanty.github.io/flashy
repo_name: flashy
repo_url: https://github.com/Inflanty/flashy
edit_uri: ""

# change directory names here
docs_dir: docs
site_dir: site
nav:
    - Home: index.md
    - About: about.md
theme: readthedocs
