# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\filebrowser.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileBrowser(object):
    def setupUi(self, FileBrowser):
        FileBrowser.setObjectName("FileBrowser")
        FileBrowser.resize(728, 432)
        self.frame = QtWidgets.QFrame(FileBrowser)
        self.frame.setGeometry(QtCore.QRect(9, 9, 711, 421))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.treeView = QtWidgets.QTreeView(self.frame)
        self.treeView.setGeometry(QtCore.QRect(0, 40, 711, 321))
        self.treeView.setObjectName("treeView")
        self.pathEdit = QtWidgets.QTextEdit(self.frame)
        self.pathEdit.setGeometry(QtCore.QRect(0, 10, 711, 21))
        self.pathEdit.setObjectName("pathEdit")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 370, 711, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openButton = QtWidgets.QPushButton(self.widget)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout.addWidget(self.openButton)
        self.cancelButton = QtWidgets.QPushButton(self.widget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)

        self.retranslateUi(FileBrowser)
        QtCore.QMetaObject.connectSlotsByName(FileBrowser)

    def retranslateUi(self, FileBrowser):
        _translate = QtCore.QCoreApplication.translate
        FileBrowser.setWindowTitle(_translate("FileBrowser", "Form"))
        self.pathEdit.setPlaceholderText(_translate("FileBrowser", "path"))
        self.openButton.setText(_translate("FileBrowser", "Open"))
        self.cancelButton.setText(_translate("FileBrowser", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FileBrowser = QtWidgets.QWidget()
    ui = Ui_FileBrowser()
    ui.setupUi(FileBrowser)
    FileBrowser.show()
    sys.exit(app.exec_())
